#!/bin/bash
function select_specific_record {
    table_name=$1

    if [ ! -f "tables/$table_name" ]; then
        zenity --error --title="Error" --text="Invalid table name "
        return
    fi

    column_names=($(awk -F':' 'NR==1 {for (i=1; i<=NF; i++) print i, $i}' "tables/$table_name"))

   
    numbered_columns=()
    for ((i=0; i<${#column_names[@]}; i+=2)); do
        numbered_columns+=("$((i/2 + 1)) ${column_names[$((i+1))]}")
    done

  
    result=$(zenity --forms --title="Select Specific Record" --text="Enter information to select specific records from $table_name" \
        --add-entry="Enter the number of Conditions : " \
        --add-list="Columns:" --list-values="$(printf "%s\n" "${numbered_columns[@]}")" \
        --separator=":")

  
    if [ $? -ne 0 ]; then
        echo "Operation canceled."
        return
    fi

   
    IFS=":" read -r num selected_columns <<< "$result"

    if [[ ! $num =~ ^[1-9][0-9]*$ || $num -gt ${#column_names[@]}/2 ]]; then
        zenity --error --title="Error" --text="Invalid input. Please enter a valid number."
        return
    fi

    arrcol=()
    arrval=()

   
    for ((i=1; i<=$num; i++)); do
        while true; do
         
            col=$(zenity --entry --title="Enter Column Number" --text="Enter column $i of condition:")

      
            if [ $? -ne 0 ]; then
                echo "Operation canceled."
                return
            fi

            if [[ $col -ge 1 && $col -le ${#column_names[@]} ]]; then
                arrcol+=("$col")  # Add the column to the array

                
                val=$(zenity --entry --title="Enter Value" --text="Enter the value for column $col:")

                if [ $? -ne 0 ]; then
                    echo "Operation canceled."
                    return
                fi

                arrval+=("$val")  # Add the value to the array
                break
            else
                zenity --error --title="Error" --text="Invalid input. Please enter a valid number."
            fi
        done
    done

    result=$(awk -F':' -v num="$num" -v cols="${arrcol[*]}" -v vals="${arrval[*]}" 'BEGIN {
        split(cols, arrcol, " ")
        split(vals, arrval, " ")
    }
    {
        match_count = 0
        for (i = 1; i <= num; i++) {
            if ($arrcol[i] == arrval[i]) {
                match_count++
            }
        }
        if (match_count > 0) {
            print $0
        }
    }' "tables/$table_name")

    zenity --info --title="Selected Records" --text="Selected records from $table_name:\n$result"
}


