#!/bin/bash
function select_specific_column {
    table_name=$1

    if [ ! -f "tables/$table_name" ]; then
        zenity --error --title="Error" --text="Invalid table name "
        return
    fi

    column_names=($(awk -F':' 'NR==1 {for (i=1; i<=NF; i++) print i, $i}' "tables/$table_name"))

    numbered_columns=()
    for ((i=0; i<${#column_names[@]}; i+=2)); do
        numbered_columns+=("$((i/2 + 1)) ${column_names[$((i+1))]}")
    done

  
    result=$(zenity --forms --title="Select Specific Columns" --text="Enter information to select specific Columns $table_name" \
        --add-entry="Number of Columns:" \
        --add-list="Columns:" --list-values="$(printf "%s\n" "${numbered_columns[@]}")" \
        --separator=":")

    if [ $? -ne 0 ]; then
        echo "Operation canceled."
        return
    fi


    IFS=":" read -r num selected_columns <<< "$result"

    if [[ ! $num =~ ^[1-9][0-9]*$ || $num -gt ${#column_names[@]}/2 ]]; then
        zenity --error --title="Error" --text="Invalid input. Please enter a valid number."
        return
    fi

    arrcol=()

  
    for ((i=1; i<=$num; i++)); do
        while true; do
           
            col=$(zenity --entry --title="Enter Column Number" --text="Enter num of column $i ")

          
            if [ $? -ne 0 ]; then
                echo "Operation canceled."
                return
            fi

            if [[ $col -ge 1 && $col -le ${#column_names[@]} ]]; then
                arrcol+=("$col")  
                break
            else
                zenity --error --title="Error" --text="Invalid input.Please enter a valid number."
            fi
        done
    done

   
    result=$(awk -F':' -v num="$num" -v cols="${arrcol[*]}"  'BEGIN {
        split(cols, arrcol, " ")
    }
    {
        for (i = 1; i <= num; i++) {
            if (i<num){
                printf "%s:", $arrcol[i]}
            else 
                printf $arrcol[i]
        }
        printf "\n"
    }' "tables/$table_name")

    zenity --info --title="Selected Columns" --text="Selected Columns from $table_name:\n$result"
}

