#!/bin/bash
directory="/home/israa/DB"
source /home/israa/functions/utilities
source /home/israa/functions/update_table
source /home/israa/functions/create_table
source /home/israa/functions/deleteFromTable
source /home/israa/functions/insert
source /home/israa/functions/delete_table
source /home/israa/functions/selectAll
source /home/israa/functions/select_record
source /home/israa/functions/select_column
function connect_menu {
    while true; do
        choice=$(zenity --list --title="Connect Menu" --text="Select an option:" \
                        --column="Options" \
                        "Create Table" "List Tables" "Drop Table" "Insert into Table" "Select from Table" "Update Table" "Delete from Table" "Main Menu" "Exit" )

        if [ $? -ne 0 ]; then
            echo "Operation canceled."
		cd /home/israa/DB
            break
        fi

        case $choice in
            "Create Table")
                create
                ;;
            "List Tables")
                list_tables_gui
                ;;
            "Drop Table")
                remove
                ;;
            "Insert into Table")
                insert
                ;;
            "Select from Table")
                select_menu
                ;;
            "Update Table")
                update_f_table
                ;;
            "Delete from Table")
                delete_f_table
                ;;
            "Main Menu")
                cd /home/israa/DB
                main_menu
                ;;
            "Exit")
                exit 0
                ;;
            *)
                zenity --error --title="Error" --text="Invalid option. Please select again."
                ;;
        esac
        if [ $? -ne 0 ]; then
            echo "Operation canceled."
            break
        fi
    done
}

function list_tables_gui {
    tables_list=$(ls tables)

    if [ $? -ne 0 ]; then
        echo "Operation canceled."
        connect_menu
        return
    fi

    zenity --list --title="Tables List" --column="Tables" $tables_list 
    
    
    if [ $? -ne 0 ]; then
        echo "Operation canceled."
        connect_menu
    fi
}

function select_menu {

    
    PS3="Enter your choice: "
    
    while true; do
        choice=$(zenity --list --title="Select Menu" --text="Choose an option" --column="Options" "Select All" "Select Specific Record" "Select Specific Column" "Back to Previous Menu" "Main Menu" "Exit")

        if [ $? -ne 0 ]; then
            echo "Operation canceled."
            return
        fi

        case $choice in
            "Select All")
                table_name=$(zenity --entry --title="Enter Table Name" --text="Enter table name:")
                select_all "$table_name"
                ;;
            "Select Specific Record")
                table_name=$(zenity --entry --title="Enter Table Name" --text="Enter table name:")
                select_specific_record "$table_name"
                ;;
            "Select Specific Column")
                table_name=$(zenity --entry --title="Enter Table Name" --text="Enter table name:")
                select_specific_column "$table_name"
                ;;
            "Back to Previous Menu")
                connect_menu
                ;;
            "Main Menu")
    cd /home/israa/DB
                main_menu
                ;;
            "Exit")
                exit 0
                ;;
            *)
                echo "Invalid choice"
                ;;
        esac
    done
}
function create_db {
    db_name=$(zenity --entry --title="Create DB" --text="Enter your DB name:")
    
    containsSpecialChars() {
        if [[ "$db_name" =~ [^a-zA-Z0-9_[:space:]] ]]; then
            return 0  
        else
            return 1  
        fi
    }

    if [[ -z "$db_name" ]] || [[ ! "${db_name:0:1}" =~ [a-zA-Z] ]] || containsSpecialChars "$db_name"; then
        zenity --error --title="Error" --text="Invalid DB name. DB name must start with a letter and cannot contain special characters except for underscores (_)"
    elif [ -d "$db_name" ]; then
        zenity --error --title="Error" --text="Error: DB '$db_name' already exists"
    else
        db_name=$(echo "$db_name" | tr ' ' '_')
        mkdir "$db_name"
        cd "$db_name"
        mkdir "tables"
        mkdir "metaData"
        cd ..
        zenity --info --title="Success" --text="$db_name DB created successfully"
    fi
}

function list_db {
    db_list=$(ls -d */ | sed 's#/##')
    zenity --info --title="List DB" --text="List of available DBs:\n$db_list"
}

function drop_db {
    db_name=$(zenity --entry --title="Drop DB" --text="Enter DB name:")

    if [[ -z "$db_name" ]] || [[ "$db_name" =~ ^[0-9] ]] || [ ! -d "$db_name" ]; then
        zenity --error --title="Error" --text="Invalid DB name"
    else
        rm -r "$db_name"
        zenity --info --title="Success" --text="$db_name dropped successfully"
    fi
}

function connect_to_db {
    db_name=$(zenity --entry --title="Connect to DB" --text="Enter DB name:")

    if [[ -z "$db_name" ]] || [[ "$db_name" =~ ^[0-9] ]] || [ ! -d "$db_name" ]; then
        zenity --error --title="Error" --text="Invalid DB name"
    else
        cd "./$db_name"
        zenity --info --title="Success" --text="You are now in $db_name DB"
        connect_menu
    fi
}

function main_menu {
    while true; do
        choice=$(zenity --list --title="Main Menu" --text="Choose an option" --column="Options" "Create DB" "List DB" "Drop DB" "Connect to DB" "Exit")

        
        if [ $? -ne 0 ]; then
            zenity --question --title="Exit Confirmation" --text="Are you sure you want to exit?" --ok-label="Yes" --cancel-label="No"

           
            if [ $? -eq 0 ]; then
                exit 0
            fi
        fi

        case $choice in
            "Create DB")
                create_db
                ;;
            "List DB")
                list_db
                ;;
            "Drop DB")
                drop_db
                ;;
            "Connect to DB")\

                connect_to_db
                ;;
            "Exit")
                zenity --question --title="Exit Confirmation" --text="Are you sure you want to exit?" --ok-label="Yes" --cancel-label="No"

              
                if [ $? -eq 0 ]; then
                    exit 0
                fi
                ;;
           
        esac
    done
}

# Check if the directory exists and create it if not
if [ -d "$directory" ]; then
    cd "$directory"
    main_menu
else
    zenity --info --text="Directory DB does not exist. Creating it"
    mkdir "$directory"
    cd "$directory"
    main_menu
fi

